version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    restart: always
    volumes:
      - ./src/logs:/app/src/logs
      - ./src/geodb:/app/src/geodb
      - ./src/templates:/app/src/templates
      - ./src/static:/app/src/static
